services:
  pgdatabase:
    image: postgres:14
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./mount_folder/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "6000:5432"
  pgadmin:
    image: dpage/pgadmin4
    volumes:
     - "./mount_folder/data_pgadmin:/var/lib/pgadmin:rw"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  